// === GENERATED by ducklink-shim-codegen — do not edit by hand ===
#![allow(dead_code, unused_imports)]

//! Aggregate-function registration via raw libduckdb-sys.
//!
//! Phase 3c (2026-06-24, unblocked once we forked duckdb-rs to
//! expose `Connection::handle()`): walks every shim aggregate
//! and wires it into DuckDB through the C API directly.
//!
//! Architecture
//!
//!   Per-aggregate-registration `ExtraInfo` allocation holds
//!   `Arc<dyn AggregateFunctionDef>`. The pointer is stashed on
//!   the duckdb_aggregate_function via
//!   `duckdb_aggregate_function_set_extra_info` and recovered
//!   in every callback via `duckdb_aggregate_function_get_extra_info`.
//!
//!   Per-group state (DuckDB allocates `state_size` bytes per
//!   group) is exactly 8 bytes: the thin pointer to a heap
//!   `Box<Box<dyn Accumulator>>`. `state_init` mints one;
//!   `state_destroy` drops it.
//!
//!   `update` walks the input chunk row-by-row, recovering the
//!   per-group accumulator via the thin pointer; `combine`
//!   merges source into target; `finalize` produces the result
//!   and writes it to the output vector slot.

use std::ffi::CString;
use std::os::raw::{c_char, c_void};
use std::sync::Arc;

use libduckdb_sys::{
    self as ffi, duckdb_aggregate_function_add_parameter, duckdb_aggregate_function_get_extra_info,
    duckdb_aggregate_function_set_error, duckdb_aggregate_function_set_extra_info,
    duckdb_aggregate_function_set_functions, duckdb_aggregate_function_set_name,
    duckdb_aggregate_function_set_return_type, duckdb_aggregate_state, duckdb_connection,
    duckdb_create_aggregate_function, duckdb_data_chunk, duckdb_destroy_aggregate_function,
    duckdb_function_info, duckdb_register_aggregate_function, duckdb_string_t, duckdb_vector,
    idx_t, DuckDBSuccess,
};

use datafission_functions::traits::{Accumulator, AggregateFunctionDef};
use datafission_functions::types::FunctionValue;

use crate::registry;

/// Per-registration state. Stashed on the aggregate via
/// duckdb_aggregate_function_set_extra_info; recovered in every
/// callback.
struct AggExtraInfo {
    def: Arc<dyn AggregateFunctionDef>,
}

/// Register every aggregate the shim publishes.
///
/// # Safety
///
/// `conn` must be a valid `duckdb_connection` for the duration
/// of this call.
pub unsafe fn register_all(conn: duckdb_connection) {
    register_aggregate(conn, "date_span_aggregate_union", "binary");
    register_aggregate(conn, "date_spanset_aggregate_union", "binary");
    register_aggregate(conn, "float_span_aggregate_union", "binary");
    register_aggregate(conn, "float_spanset_aggregate_union", "binary");
    register_aggregate(conn, "int_span_aggregate_union", "binary");
    register_aggregate(conn, "int_spanset_aggregate_union", "binary");
    register_aggregate(conn, "tbigint_count_aggregate", "binary");
    register_aggregate(conn, "tbigint_max_value_aggregate", "binary");
    register_aggregate(conn, "tbigint_merge_agg", "binary");
    register_aggregate(conn, "tbigint_min_value_aggregate", "binary");
    register_aggregate(conn, "tbigint_range_aggregate", "binary");
    register_aggregate(conn, "tbigint_sum_aggregate", "binary");
    register_aggregate(conn, "tbool_merge_agg", "binary");
    register_aggregate(conn, "tbool_temporal_and", "binary");
    register_aggregate(conn, "tand", "binary"); // alias of tbool_temporal_and
    register_aggregate(conn, "tbool_temporal_or", "binary");
    register_aggregate(conn, "tor", "binary"); // alias of tbool_temporal_or
    register_aggregate(conn, "tcbuffer_merge_agg", "binary");
    register_aggregate(conn, "tcbuffer_temporal_count", "binary");
    register_aggregate(conn, "tfloat_merge_agg", "binary");
    register_aggregate(conn, "tfloat_temporal_avg", "binary");
    register_aggregate(conn, "tavg", "binary"); // alias of tfloat_temporal_avg
    register_aggregate(conn, "tfloat_temporal_count", "binary");
    register_aggregate(conn, "tcount", "binary"); // alias of tfloat_temporal_count
    register_aggregate(conn, "tfloat_temporal_max", "binary");
    register_aggregate(conn, "tmax", "binary"); // alias of tfloat_temporal_max
    register_aggregate(conn, "tfloat_temporal_min", "binary");
    register_aggregate(conn, "tmin", "binary"); // alias of tfloat_temporal_min
    register_aggregate(conn, "tfloat_temporal_sum", "binary");
    register_aggregate(conn, "tsum", "binary"); // alias of tfloat_temporal_sum
    register_aggregate(conn, "tfloat_total", "binary");
    register_aggregate(conn, "tfloat_variance_agg", "binary");
    register_aggregate(conn, "tfloat_variance_aggregate", "binary");
    register_aggregate(conn, "tgeogpoint_merge_agg", "binary");
    register_aggregate(conn, "tgeogpoint_temporal_count", "binary");
    register_aggregate(conn, "tgeography_merge_agg", "binary");
    register_aggregate(conn, "tgeometry_merge_agg", "binary");
    register_aggregate(conn, "tgeompoint3d_merge_agg", "binary");
    register_aggregate(conn, "tgeompoint_centroid_agg", "binary");
    register_aggregate(conn, "tgeompoint_merge_agg", "binary");
    register_aggregate(conn, "tgeompoint_st_extent", "binary");
    register_aggregate(conn, "tgeompoint_temporal_centroid", "binary");
    register_aggregate(conn, "tgeompoint_temporal_count", "binary");
    register_aggregate(conn, "tint_count_agg", "binary");
    register_aggregate(conn, "tint_count_aggregate", "binary");
    register_aggregate(conn, "tint_max_agg", "binary");
    register_aggregate(conn, "tint_max_value_agg", "binary");
    register_aggregate(conn, "tint_max_value_aggregate", "binary");
    register_aggregate(conn, "tint_merge_agg", "binary");
    register_aggregate(conn, "tint_min_agg", "binary");
    register_aggregate(conn, "tint_min_value_agg", "binary");
    register_aggregate(conn, "tint_min_value_aggregate", "binary");
    register_aggregate(conn, "tint_range_agg", "binary");
    register_aggregate(conn, "tint_range_aggregate", "binary");
    register_aggregate(conn, "tint_sum_agg", "binary");
    register_aggregate(conn, "tint_temporal_max", "binary");
    register_aggregate(conn, "tint_temporal_min", "binary");
    register_aggregate(conn, "tint_temporal_sum", "binary");
    register_aggregate(conn, "tnpoint_merge_agg", "binary");
    register_aggregate(conn, "tnpoint_temporal_count", "binary");
    register_aggregate(conn, "tpose_merge_agg", "binary");
    register_aggregate(conn, "tpose_temporal_count", "binary");
    register_aggregate(conn, "tstz_span_aggregate_union", "binary");
    register_aggregate(conn, "tstz_spanset_aggregate_union", "binary");
    register_aggregate(conn, "ttext_concat_agg", "binary");
    register_aggregate(conn, "ttext_concat_aggregate", "binary");
    register_aggregate(conn, "ttext_merge_agg", "binary");
    // Phase 3c: 60 canonical + 7 alias names registered.
}

unsafe fn register_aggregate(conn: duckdb_connection, sql_name: &str, input_ty: &str) {
    let def = match registry::lookup_aggregate(sql_name) {
        Some(d) => d,
        None => {
            eprintln!("[shim-aggregates] no shim entry for `{sql_name}` — skipping");
            return;
        }
    };

    let agg = duckdb_create_aggregate_function();
    let name_cs = match CString::new(sql_name) {
        Ok(c) => c,
        Err(_) => {
            eprintln!("[shim-aggregates] name contains NUL: `{sql_name}` — skipping");
            duckdb_destroy_aggregate_function(&mut { agg });
            return;
        }
    };
    duckdb_aggregate_function_set_name(agg, name_cs.as_ptr());

    // Input type from the shim's recorded param signature; most
    // postgis aggregates are unary blob (ST_Union, ST_Extent, ...)
    // but the mobilitydb F64 aggregates (tfloat_max_agg / etc.)
    // take a scalar f64. Return type stays BLOB by default — the
    // dispatch path converts every scalar result to bytes; users
    // who want the typed value can wrap with `tfloat_to_text` or
    // similar.
    let in_id = match input_ty {
        "float64" => ffi::DUCKDB_TYPE_DUCKDB_TYPE_DOUBLE,
        "float32" => ffi::DUCKDB_TYPE_DUCKDB_TYPE_FLOAT,
        "int64" => ffi::DUCKDB_TYPE_DUCKDB_TYPE_BIGINT,
        "int32" => ffi::DUCKDB_TYPE_DUCKDB_TYPE_INTEGER,
        "uint64" => ffi::DUCKDB_TYPE_DUCKDB_TYPE_UBIGINT,
        "uint32" => ffi::DUCKDB_TYPE_DUCKDB_TYPE_UINTEGER,
        "boolean" => ffi::DUCKDB_TYPE_DUCKDB_TYPE_BOOLEAN,
        "text" => ffi::DUCKDB_TYPE_DUCKDB_TYPE_VARCHAR,
        _ => ffi::DUCKDB_TYPE_DUCKDB_TYPE_BLOB,
    };
    let in_lt = ffi::duckdb_create_logical_type(in_id);
    duckdb_aggregate_function_add_parameter(agg, in_lt);
    let ret_lt = ffi::duckdb_create_logical_type(ffi::DUCKDB_TYPE_DUCKDB_TYPE_BLOB);
    duckdb_aggregate_function_set_return_type(agg, ret_lt);
    // Both add_parameter and set_return_type take the type by
    // value and DuckDB clones it internally, so we still own
    // the handles and must destroy them after use.
    let mut in_to_destroy = in_lt;
    ffi::duckdb_destroy_logical_type(&mut in_to_destroy);
    let mut ret_to_destroy = ret_lt;
    ffi::duckdb_destroy_logical_type(&mut ret_to_destroy);

    // Wire the callbacks (state_size + state_init + update +
    // combine + finalize). state_destroy goes through the
    // separate set_destructor API — see drop_state below.
    duckdb_aggregate_function_set_functions(
        agg,
        Some(state_size),
        Some(state_init),
        Some(update_callback),
        Some(combine_callback),
        Some(finalize_callback),
    );
    ffi::duckdb_aggregate_function_set_destructor(agg, Some(state_destroy));

    // Park the per-registration state. The Box is leaked here
    // and reclaimed when DuckDB calls the destructor.
    let extra = Box::into_raw(Box::new(AggExtraInfo {
        def: Arc::clone(&def),
    }));
    duckdb_aggregate_function_set_extra_info(agg, extra as *mut c_void, Some(drop_extra_info));

    let rc = duckdb_register_aggregate_function(conn, agg);
    duckdb_destroy_aggregate_function(&mut { agg });
    if rc != DuckDBSuccess {
        // Scalar/aggregate name clashes (st_collect, st_union,
        // st_clusterwithin, st_clusterdbscan,
        // st_clusterintersecting, tfloat_sum, tint_sum, …) are
        // resolved in favour of the AGGREGATE: scalars.rs skips
        // any name also published as an aggregate, so this
        // registration normally succeeds. A non-success rc here
        // therefore means a genuine catalog conflict (e.g. a
        // built-in DuckDB aggregate of the same name) — log and
        // continue so the rest still register.
        eprintln!(
            "[shim-aggregates] could not register aggregate `{sql_name}` (rc={rc}); \
             a built-in of the same name may already exist"
        );
    }
}

// =====================================================================
// C callbacks. All `unsafe extern "C"` because DuckDB calls them.
//
// State layout: each per-group state is exactly 8 bytes — a
// thin pointer to a heap-allocated `Box<dyn Accumulator>`.
// `state_init` mints one; `state_destroy` drops it. We use
// Box<dyn Accumulator> directly (fat ptr → 16 bytes) but stored
// behind one more Box layer so the THIN pointer is what lives
// in the state slot.
// =====================================================================

type AccBoxPtr = *mut Box<dyn Accumulator>;

unsafe extern "C" fn state_size(_info: duckdb_function_info) -> idx_t {
    std::mem::size_of::<AccBoxPtr>() as idx_t
}

unsafe extern "C" fn state_init(info: duckdb_function_info, state: duckdb_aggregate_state) {
    let extra = extra_info_typed(info);
    let acc: Box<dyn Accumulator> = extra.def.create_accumulator();
    let thin: AccBoxPtr = Box::into_raw(Box::new(acc));
    // The state pointer points to STATE_SIZE bytes that DuckDB
    // owns. Treat it as a slot for our thin pointer.
    let slot = state as *mut AccBoxPtr;
    std::ptr::write(slot, thin);
}

unsafe extern "C" fn state_destroy(states: *mut duckdb_aggregate_state, count: idx_t) {
    if states.is_null() {
        return;
    }
    for i in 0..count as usize {
        let state_ptr: duckdb_aggregate_state = std::ptr::read(states.add(i));
        if state_ptr.is_null() {
            continue;
        }
        let slot = state_ptr as *mut AccBoxPtr;
        let thin = std::ptr::read(slot);
        if !thin.is_null() {
            drop(Box::from_raw(thin));
        }
    }
}

unsafe extern "C" fn update_callback(
    info: duckdb_function_info,
    input: duckdb_data_chunk,
    states: *mut duckdb_aggregate_state,
) {
    match std::panic::catch_unwind(|| update_inner(info, input, states)) {
        Ok(Ok(())) => {}
        Ok(Err(msg)) => set_error(info, &msg),
        Err(_) => set_error(info, "panic in aggregate update"),
    }
}

unsafe fn update_inner(
    info: duckdb_function_info,
    input: duckdb_data_chunk,
    states: *mut duckdb_aggregate_state,
) -> std::result::Result<(), String> {
    use datafission_functions::DataType;
    let n = ffi::duckdb_data_chunk_get_size(input) as usize;
    let v0 = ffi::duckdb_data_chunk_get_vector(input, 0);
    let validity = ffi::duckdb_vector_get_validity(v0);

    // Dispatch on the recorded input type. The aggregate's
    // ExtraInfo wraps `Arc<dyn AggregateFunctionDef>`; we read
    // its first parameter type to decide how to interpret the
    // vector's raw memory.
    let extra = extra_info_typed(info);
    let in_ty = extra
        .def
        .param_types()
        .first()
        .and_then(|sig| sig.first().cloned())
        .unwrap_or(DataType::Binary);

    macro_rules! prim_loop {
        ($ty:ty, $variant:ident) => {{
            let data = ffi::duckdb_vector_get_data(v0) as *const $ty;
            for i in 0..n {
                if !validity.is_null() && !ffi::duckdb_validity_row_is_valid(validity, i as idx_t) {
                    continue;
                }
                let val = std::ptr::read(data.add(i));
                let acc_ptr = read_state(states, i);
                let acc = &mut *acc_ptr;
                acc.accumulate(&FunctionValue::$variant(val))
                    .map_err(|e| format!("{e:?}"))?;
            }
        }};
    }

    match in_ty {
        DataType::Float64 => prim_loop!(f64, Float64),
        DataType::Float32 => prim_loop!(f32, Float32),
        DataType::Int64 => prim_loop!(i64, Int64),
        DataType::Int32 => prim_loop!(i32, Int32),
        DataType::UInt64 => prim_loop!(u64, UInt64),
        DataType::UInt32 => prim_loop!(u32, UInt32),
        DataType::Boolean => prim_loop!(bool, Boolean),
        DataType::Text => {
            let data = ffi::duckdb_vector_get_data(v0) as *const duckdb_string_t;
            for i in 0..n {
                if !validity.is_null() && !ffi::duckdb_validity_row_is_valid(validity, i as idx_t) {
                    continue;
                }
                let mut s_raw: duckdb_string_t = std::ptr::read(data.add(i));
                let bytes = read_string_t_bytes(&mut s_raw);
                let s = String::from_utf8_lossy(&bytes).into_owned();
                let acc_ptr = read_state(states, i);
                let acc = &mut *acc_ptr;
                acc.accumulate(&FunctionValue::String(s))
                    .map_err(|e| format!("{e:?}"))?;
            }
        }
        _ => {
            // Default: Binary/Blob — original path.
            let data = ffi::duckdb_vector_get_data(v0) as *const duckdb_string_t;
            for i in 0..n {
                if !validity.is_null() && !ffi::duckdb_validity_row_is_valid(validity, i as idx_t) {
                    continue;
                }
                let mut s_raw: duckdb_string_t = std::ptr::read(data.add(i));
                let bytes = read_string_t_bytes(&mut s_raw);
                let acc_ptr = read_state(states, i);
                let acc = &mut *acc_ptr;
                acc.accumulate(&FunctionValue::Binary(bytes))
                    .map_err(|e| format!("{e:?}"))?;
            }
        }
    }
    Ok(())
}

/// Decode a `duckdb_string_t` (DuckDB's inline-or-pointer
/// string struct) into an owned `Vec<u8>`. Works for both
/// inlined (≤12 bytes) and pointer-backed strings; the C API
/// hides the discriminant for us.
unsafe fn read_string_t_bytes(s: &mut duckdb_string_t) -> Vec<u8> {
    let len = ffi::duckdb_string_t_length(*s) as usize;
    if len == 0 {
        return Vec::new();
    }
    let p = ffi::duckdb_string_t_data(s as *mut duckdb_string_t);
    std::slice::from_raw_parts(p as *const u8, len).to_vec()
}

unsafe extern "C" fn combine_callback(
    info: duckdb_function_info,
    source: *mut duckdb_aggregate_state,
    target: *mut duckdb_aggregate_state,
    count: idx_t,
) {
    let result = std::panic::catch_unwind(|| {
        for i in 0..count as usize {
            let src = read_state(source, i);
            let tgt = read_state(target, i);
            if src.is_null() || tgt.is_null() {
                continue;
            }
            let src_acc: &dyn Accumulator = &**src;
            let tgt_acc = &mut **tgt;
            tgt_acc.merge(src_acc).map_err(|e| format!("{e:?}"))?;
        }
        Ok::<(), String>(())
    });
    match result {
        Ok(Ok(())) => {}
        Ok(Err(msg)) => set_error(info, &msg),
        Err(_) => set_error(info, "panic in aggregate combine"),
    }
}

unsafe extern "C" fn finalize_callback(
    info: duckdb_function_info,
    source: *mut duckdb_aggregate_state,
    result: duckdb_vector,
    count: idx_t,
    offset: idx_t,
) {
    match std::panic::catch_unwind(|| finalize_inner(info, source, result, count, offset)) {
        Ok(Ok(())) => {}
        Ok(Err(msg)) => set_error(info, &msg),
        Err(_) => set_error(info, "panic in aggregate finalize"),
    }
}

unsafe fn finalize_inner(
    _info: duckdb_function_info,
    source: *mut duckdb_aggregate_state,
    result: duckdb_vector,
    count: idx_t,
    offset: idx_t,
) -> std::result::Result<(), String> {
    for i in 0..count as usize {
        let dst = offset as usize + i;
        let acc_ptr = read_state(source, i);
        if acc_ptr.is_null() {
            vector_set_null(result, dst);
            continue;
        }
        let acc = &**acc_ptr;
        let value = acc.finalize().map_err(|e| format!("{e:?}"))?;
        // Output type is BLOB by construction (aggregates_rs sets the
        // return type to LogicalTypeId::Blob unconditionally). Encode
        // primitives as their little-endian bytes — callers that want
        // the typed value can apply `octet_length()` to confirm width
        // or unhex back to a primitive via DuckDB's bit ops.
        match value {
            FunctionValue::Binary(b) => vector_assign_bytes(result, dst, &b),
            FunctionValue::String(s) => vector_assign_bytes(result, dst, s.as_bytes()),
            FunctionValue::Float64(v) => vector_assign_bytes(result, dst, &v.to_le_bytes()),
            FunctionValue::Float32(v) => vector_assign_bytes(result, dst, &v.to_le_bytes()),
            FunctionValue::Int64(v) => vector_assign_bytes(result, dst, &v.to_le_bytes()),
            FunctionValue::Int32(v) => vector_assign_bytes(result, dst, &v.to_le_bytes()),
            FunctionValue::UInt64(v) => vector_assign_bytes(result, dst, &v.to_le_bytes()),
            FunctionValue::UInt32(v) => vector_assign_bytes(result, dst, &v.to_le_bytes()),
            FunctionValue::Boolean(v) => vector_assign_bytes(result, dst, &[v as u8]),
            FunctionValue::Null => vector_set_null(result, dst),
            other => {
                return Err(format!(
                    "aggregate finalize: unexpected result variant `{}`",
                    other.type_name()
                ))
            }
        }
    }
    Ok(())
}

/// Write `bytes` into the `dst`-th slot of `result` (a BLOB or
/// VARCHAR output vector). DuckDB copies the bytes internally,
/// so the caller's `bytes` can be dropped after this call.
unsafe fn vector_assign_bytes(result: duckdb_vector, dst: usize, bytes: &[u8]) {
    ffi::duckdb_vector_assign_string_element_len(
        result,
        dst as idx_t,
        bytes.as_ptr() as *const c_char,
        bytes.len() as idx_t,
    );
}

/// Mark the `dst`-th slot of `result` as SQL NULL.
unsafe fn vector_set_null(result: duckdb_vector, dst: usize) {
    ffi::duckdb_vector_ensure_validity_writable(result);
    let validity = ffi::duckdb_vector_get_validity(result);
    if !validity.is_null() {
        ffi::duckdb_validity_set_row_invalid(validity, dst as idx_t);
    }
}

unsafe extern "C" fn drop_extra_info(ptr: *mut c_void) {
    if ptr.is_null() {
        return;
    }
    drop(Box::from_raw(ptr as *mut AggExtraInfo));
}

// =====================================================================
// State-slot accessors.
// =====================================================================

unsafe fn read_state(states: *mut duckdb_aggregate_state, idx: usize) -> AccBoxPtr {
    // `states[i]` is a duckdb_aggregate_state (a pointer to the
    // per-group state slot). Dereference to get the slot
    // address, then read our AccBoxPtr out of the slot.
    //
    // (Initial implementation skipped the dereference and
    // crashed DuckDB with SIGBUS — the C API docs say:
    //   "states – a pointer to states – Each element points to
    //    the state for the corresponding input row."
    //  i.e. it's an array of state pointers, not the states
    //  themselves laid out contiguously.)
    let state_ptr: duckdb_aggregate_state = std::ptr::read(states.add(idx));
    let slot = state_ptr as *mut AccBoxPtr;
    std::ptr::read(slot)
}

unsafe fn extra_info_typed<'a>(info: duckdb_function_info) -> &'a AggExtraInfo {
    let raw = duckdb_aggregate_function_get_extra_info(info);
    &*(raw as *const AggExtraInfo)
}

unsafe fn set_error(info: duckdb_function_info, msg: &str) {
    if let Ok(cs) = CString::new(msg) {
        duckdb_aggregate_function_set_error(info, cs.as_ptr() as *const c_char);
    }
}
