// === GENERATED by ducklink-shim-codegen — do not edit by hand ===
#![allow(dead_code, unused_imports)]

//! CAST(x AS T) — identity casts for shim-published alias types.
//!
//! ## Phase 4d (this pass) — BLOB <-> alias identity casts
//!
//! Because every shim-published type (GEOMETRY, GEOGRAPHY,
//! STBOX, ...) is registered as an alias of BLOB
//! (`types::register_all`), the wire format is identical;
//! casts between BLOB and any alias are bytewise no-ops. Without
//! registering them, DuckDB rejects every
//! `CREATE TABLE t (g GEOMETRY); INSERT INTO t VALUES
//! (ST_GeomFromText(...))` with "Unimplemented type for cast
//! (BLOB -> GEOMETRY)" since the function returns BLOB and the
//! column expects GEOMETRY.
//!
//! Per alias name N, we register two casts:
//!   - BLOB -> N   (implicit cast, allows INSERT INTO t (N) VALUES (blob_fn(...)))
//!   - N -> BLOB   (implicit cast, allows blob_fn(t.n_column))
//!
//! Both share a single identity callback: read each row's
//! string_t from the input vector, write the same bytes to the
//! output via `duckdb_vector_assign_string_element_len`. The
//! callback is reused across every registered cast.
//!
//! ## Out of scope for this pass — functional casts
//!
//! Casts like `CAST(text AS GEOMETRY) -> ST_GeomFromText(text)`
//! are source-shape driven (depends on what the source expression
//! IS, not just its type). DuckDB's cast hooks are type-driven,
//! so those rewrites belong in `shim-sql-preprocess` at the AST
//! layer, which already handles them.

use libduckdb_sys::{
    self as ffi, duckdb_connection, duckdb_data_chunk_get_size, duckdb_function_info,
    duckdb_string_t, duckdb_validity_row_is_valid, duckdb_validity_set_row_invalid, duckdb_vector,
    duckdb_vector_assign_string_element_len, duckdb_vector_ensure_validity_writable,
    duckdb_vector_get_data, duckdb_vector_get_validity, idx_t, DuckDBSuccess,
};
use std::ffi::CString;
use std::os::raw::c_char;

/// Register every BLOB <-> alias identity cast the shim
/// publishes via `column_types`.
///
/// # Safety
///
/// `con` must be a valid `duckdb_connection` for the duration
/// of this call.
pub unsafe fn register_all(con: duckdb_connection) {
    if con.is_null() {
        return;
    }
    register_identity_cast(
        con,
        "mobilitydb:temporal@0.1.0/bitemporal-bool-ops/bitemporal-bool-instant",
    );
    register_identity_cast(
        con,
        "mobilitydb:temporal@0.1.0/bitemporal-bool-ops/bitemporal-bool-sequence",
    );
    register_identity_cast(
        con,
        "mobilitydb:temporal@0.1.0/bitemporal-float-ops/bitemporal-float-instant",
    );
    register_identity_cast(
        con,
        "mobilitydb:temporal@0.1.0/bitemporal-float-ops/bitemporal-float-sequence",
    );
    register_identity_cast(
        con,
        "mobilitydb:temporal@0.1.0/bitemporal-int-ops/bitemporal-int-instant",
    );
    register_identity_cast(
        con,
        "mobilitydb:temporal@0.1.0/bitemporal-int-ops/bitemporal-int-sequence",
    );
    register_identity_cast(
        con,
        "mobilitydb:temporal@0.1.0/bitemporal-text-ops/bitemporal-text-instant",
    );
    register_identity_cast(
        con,
        "mobilitydb:temporal@0.1.0/bitemporal-text-ops/bitemporal-text-sequence",
    );
    register_identity_cast(
        con,
        "mobilitydb:temporal@0.1.0/clustering-ops/cluster-point",
    );
    register_identity_cast(con, "mobilitydb:temporal@0.1.0/join-ops/joined-float-pair");
    register_identity_cast(
        con,
        "mobilitydb:temporal@0.1.0/nearest-join-ops/nearest-bool-pair",
    );
    register_identity_cast(
        con,
        "mobilitydb:temporal@0.1.0/nearest-join-ops/nearest-float-pair",
    );
    register_identity_cast(
        con,
        "mobilitydb:temporal@0.1.0/nearest-join-ops/nearest-int-pair",
    );
    register_identity_cast(
        con,
        "mobilitydb:temporal@0.1.0/nearest-join-ops/nearest-text-pair",
    );
    register_identity_cast(
        con,
        "mobilitydb:temporal@0.1.0/other-indexes-ops/indexed-interval",
    );
    register_identity_cast(
        con,
        "mobilitydb:temporal@0.1.0/other-indexes-ops/indexed-point-xy",
    );
    register_identity_cast(
        con,
        "mobilitydb:temporal@0.1.0/other-indexes-ops/indexed-point-xyz",
    );
    register_identity_cast(con, "mobilitydb:temporal@0.1.0/pattern-ops/crossing-info");
    register_identity_cast(
        con,
        "mobilitydb:temporal@0.1.0/pattern-ops/level-crossing-info",
    );
    register_identity_cast(con, "mobilitydb:temporal@0.1.0/pattern-ops/peak-info");
    register_identity_cast(
        con,
        "mobilitydb:temporal@0.1.0/sequence-json-ops/sequence-json-row",
    );
    register_identity_cast(con, "mobilitydb:temporal@0.1.0/spans-ops/date-span");
    register_identity_cast(con, "mobilitydb:temporal@0.1.0/spans-ops/float-span");
    register_identity_cast(con, "mobilitydb:temporal@0.1.0/spans-ops/int-span");
    register_identity_cast(
        con,
        "mobilitydb:temporal@0.1.0/spatial-index-ops/spatial-index-match",
    );
    register_identity_cast(con, "mobilitydb:temporal@0.1.0/statistics-ops/anomaly-info");
    register_identity_cast(
        con,
        "mobilitydb:temporal@0.1.0/statistics-ops/histogram-bin",
    );
    register_identity_cast(con, "mobilitydb:temporal@0.1.0/statistics-ops/kde-point");
    register_identity_cast(
        con,
        "mobilitydb:temporal@0.1.0/statistics-ops/level-crossing-info",
    );
    register_identity_cast(con, "mobilitydb:temporal@0.1.0/statistics-ops/peak-info");
    register_identity_cast(
        con,
        "mobilitydb:temporal@0.1.0/statistics-ops/zero-crossing-info",
    );
    register_identity_cast(con, "mobilitydb:temporal@0.1.0/stbox-ops/stbox");
    register_identity_cast(con, "mobilitydb:temporal@0.1.0/stbox-ops/stbox3d");
    register_identity_cast(con, "mobilitydb:temporal@0.1.0/stbox-ops/tbox");
    register_identity_cast(con, "mobilitydb:temporal@0.1.0/stbox3d-ops/stbox3d");
    register_identity_cast(con, "mobilitydb:temporal@0.1.0/stindex-ops/stindex-entry");
    register_identity_cast(
        con,
        "mobilitydb:temporal@0.1.0/tbigint-math-ops/tbigint-value-bucket",
    );
    register_identity_cast(con, "mobilitydb:temporal@0.1.0/tbigint-ops/tbigint-instant");
    register_identity_cast(
        con,
        "mobilitydb:temporal@0.1.0/tbigint-ops/tbigint-sequence",
    );
    register_identity_cast(con, "mobilitydb:temporal@0.1.0/tbool-ops/tbool-instant");
    register_identity_cast(con, "mobilitydb:temporal@0.1.0/tbool-ops/tbool-sequence");
    register_identity_cast(con, "mobilitydb:temporal@0.1.0/tcbuffer-ops/cbuffer");
    register_identity_cast(con, "mobilitydb:temporal@0.1.0/tcbuffer-ops/cbuffer-bbox");
    register_identity_cast(
        con,
        "mobilitydb:temporal@0.1.0/tcbuffer-ops/tcbuffer-instant",
    );
    register_identity_cast(
        con,
        "mobilitydb:temporal@0.1.0/tcbuffer-ops/tcbuffer-sequence",
    );
    register_identity_cast(
        con,
        "mobilitydb:temporal@0.1.0/temporal-index-ops/temporal-index-match",
    );
    register_identity_cast(con, "mobilitydb:temporal@0.1.0/tgeogpoint-ops/geog-point");
    register_identity_cast(
        con,
        "mobilitydb:temporal@0.1.0/tgeogpoint-ops/tgeogpoint-instant",
    );
    register_identity_cast(
        con,
        "mobilitydb:temporal@0.1.0/tgeogpoint-ops/tgeogpoint-sequence",
    );
    register_identity_cast(con, "mobilitydb:temporal@0.1.0/tgeography-ops/geography");
    register_identity_cast(
        con,
        "mobilitydb:temporal@0.1.0/tgeography-ops/tgeography-instant",
    );
    register_identity_cast(
        con,
        "mobilitydb:temporal@0.1.0/tgeography-ops/tgeography-sequence",
    );
    register_identity_cast(con, "mobilitydb:temporal@0.1.0/tgeometry-ops/geometry");
    register_identity_cast(
        con,
        "mobilitydb:temporal@0.1.0/tgeometry-ops/tgeometry-instant",
    );
    register_identity_cast(
        con,
        "mobilitydb:temporal@0.1.0/tgeometry-ops/tgeometry-point-instant",
    );
    register_identity_cast(
        con,
        "mobilitydb:temporal@0.1.0/tgeometry-ops/tgeometry-point-sequence",
    );
    register_identity_cast(
        con,
        "mobilitydb:temporal@0.1.0/tgeometry-ops/tgeometry-sequence",
    );
    register_identity_cast(
        con,
        "mobilitydb:temporal@0.1.0/tgeompoint-ops/direction-stats",
    );
    register_identity_cast(
        con,
        "mobilitydb:temporal@0.1.0/tgeompoint-ops/movement-summary",
    );
    register_identity_cast(con, "mobilitydb:temporal@0.1.0/tgeompoint-ops/speed-stats");
    register_identity_cast(
        con,
        "mobilitydb:temporal@0.1.0/tgeompoint-ops/trajectory-analysis",
    );
    register_identity_cast(
        con,
        "mobilitydb:temporal@0.1.0/tgeompoint3d-ops/geom-point3d",
    );
    register_identity_cast(
        con,
        "mobilitydb:temporal@0.1.0/tgeompoint3d-ops/tgeompoint3d-instant",
    );
    register_identity_cast(
        con,
        "mobilitydb:temporal@0.1.0/tgeompoint3d-ops/tgeompoint3d-sequence",
    );
    register_identity_cast(
        con,
        "mobilitydb:temporal@0.1.0/time-split-ops/tfloat-time-bucket",
    );
    register_identity_cast(
        con,
        "mobilitydb:temporal@0.1.0/time-split-ops/tint-time-bucket",
    );
    register_identity_cast(con, "mobilitydb:temporal@0.1.0/tjsonb-ops/jsonb-value");
    register_identity_cast(con, "mobilitydb:temporal@0.1.0/tjsonb-ops/tjsonb-instant");
    register_identity_cast(con, "mobilitydb:temporal@0.1.0/tjsonb-ops/tjsonb-sequence");
    register_identity_cast(
        con,
        "mobilitydb:temporal@0.1.0/tnpoint-complete-ops/route-change-event",
    );
    register_identity_cast(
        con,
        "mobilitydb:temporal@0.1.0/tnpoint-complete-ops/route-distance",
    );
    register_identity_cast(
        con,
        "mobilitydb:temporal@0.1.0/tnpoint-complete-ops/route-duration",
    );
    register_identity_cast(
        con,
        "mobilitydb:temporal@0.1.0/tnpoint-complete-ops/tnpoint-route-segment",
    );
    register_identity_cast(
        con,
        "mobilitydb:temporal@0.1.0/tnpoint-complete-ops/tnpoint-stop-event",
    );
    register_identity_cast(con, "mobilitydb:temporal@0.1.0/tnpoint-ops/npoint");
    register_identity_cast(con, "mobilitydb:temporal@0.1.0/tnpoint-ops/nsegment");
    register_identity_cast(con, "mobilitydb:temporal@0.1.0/tnpoint-ops/tnpoint-instant");
    register_identity_cast(
        con,
        "mobilitydb:temporal@0.1.0/tnpoint-ops/tnpoint-sequence",
    );
    register_identity_cast(con, "mobilitydb:temporal@0.1.0/to-rows-ops/tcbuffer-row");
    register_identity_cast(con, "mobilitydb:temporal@0.1.0/to-rows-ops/tgeogpoint-row");
    register_identity_cast(con, "mobilitydb:temporal@0.1.0/to-rows-ops/tgeompoint-row");
    register_identity_cast(
        con,
        "mobilitydb:temporal@0.1.0/to-rows-ops/tgeompoint3d-row",
    );
    register_identity_cast(con, "mobilitydb:temporal@0.1.0/to-rows-ops/tpose-row");
    register_identity_cast(con, "mobilitydb:temporal@0.1.0/tpose-ops/pose2d");
    register_identity_cast(con, "mobilitydb:temporal@0.1.0/tpose-ops/tpose-instant");
    register_identity_cast(con, "mobilitydb:temporal@0.1.0/tpose-ops/tpose-sequence");
    register_identity_cast(con, "mobilitydb:temporal@0.1.0/tstzspan-ops/tstzspan");
    register_identity_cast(con, "mobilitydb:temporal@0.1.0/ttext-ops/ttext-instant");
    register_identity_cast(con, "mobilitydb:temporal@0.1.0/ttext-ops/ttext-sequence");
    register_identity_cast(
        con,
        "mobilitydb:temporal@0.1.0/typed-join-ops/joined-bool-pair",
    );
    register_identity_cast(
        con,
        "mobilitydb:temporal@0.1.0/typed-join-ops/joined-int-pair",
    );
    register_identity_cast(
        con,
        "mobilitydb:temporal@0.1.0/typed-join-ops/joined-text-pair",
    );
    register_identity_cast(con, "mobilitydb:temporal@0.1.0/types/bounding-box");
    register_identity_cast(con, "mobilitydb:temporal@0.1.0/types/geom-point");
    register_identity_cast(con, "mobilitydb:temporal@0.1.0/types/tfloat-instant");
    register_identity_cast(con, "mobilitydb:temporal@0.1.0/types/tfloat-sequence");
    register_identity_cast(con, "mobilitydb:temporal@0.1.0/types/tgeompoint-instant");
    register_identity_cast(con, "mobilitydb:temporal@0.1.0/types/tgeompoint-sequence");
    register_identity_cast(con, "mobilitydb:temporal@0.1.0/types/time-period");
    register_identity_cast(con, "mobilitydb:temporal@0.1.0/types/tint-instant");
    register_identity_cast(con, "mobilitydb:temporal@0.1.0/types/tint-sequence");
    register_identity_cast(
        con,
        "mobilitydb:temporal@0.1.0/value-split-ops/tfloat-value-bucket",
    );
    register_identity_cast(
        con,
        "mobilitydb:temporal@0.1.0/value-split-ops/tint-value-bucket",
    );
}

unsafe fn register_identity_cast(con: duckdb_connection, alias: &str) {
    let blob = ffi::duckdb_create_logical_type(ffi::DUCKDB_TYPE_DUCKDB_TYPE_BLOB);
    let aliased = ffi::duckdb_create_logical_type(ffi::DUCKDB_TYPE_DUCKDB_TYPE_BLOB);
    if blob.is_null() || aliased.is_null() {
        eprintln!("[shim-casts] could not create logical type for {alias}");
        return;
    }
    let c_alias = match CString::new(alias) {
        Ok(c) => c,
        Err(_) => {
            eprintln!("[shim-casts] alias name contains NUL: {alias}");
            let (mut a, mut b) = (aliased, blob);
            ffi::duckdb_destroy_logical_type(&mut a);
            ffi::duckdb_destroy_logical_type(&mut b);
            return;
        }
    };
    ffi::duckdb_logical_type_set_alias(aliased, c_alias.as_ptr());

    // BLOB -> alias
    register_one_direction(con, blob, aliased, alias, "blob_to_alias");
    // alias -> BLOB
    register_one_direction(con, aliased, blob, alias, "alias_to_blob");

    let (mut a, mut b) = (aliased, blob);
    ffi::duckdb_destroy_logical_type(&mut a);
    ffi::duckdb_destroy_logical_type(&mut b);
}

unsafe fn register_one_direction(
    con: duckdb_connection,
    source: ffi::duckdb_logical_type,
    target: ffi::duckdb_logical_type,
    alias: &str,
    direction: &str,
) {
    let cast = ffi::duckdb_create_cast_function();
    ffi::duckdb_cast_function_set_source_type(cast, source);
    ffi::duckdb_cast_function_set_target_type(cast, target);
    // Cost of 1 — explicit casts always free; implicit casts
    // prefer this over more-expensive paths but DuckDB's own
    // built-ins (cost 0) still win where they apply.
    ffi::duckdb_cast_function_set_implicit_cast_cost(cast, 1);
    ffi::duckdb_cast_function_set_function(cast, Some(identity_cast_callback));

    let rc = ffi::duckdb_register_cast_function(con, cast);
    let mut c = cast;
    ffi::duckdb_destroy_cast_function(&mut c);
    if rc != DuckDBSuccess {
        eprintln!(
            "[shim-casts] {direction} for {alias} failed (rc={rc}) — \
             may already be registered or a built-in handles it"
        );
    }
}

/// Per-row identity copy: every BLOB-shaped value is bytewise
/// identical between the source and target representations
/// because both sides are LogicalTypeId::Blob. We just memcpy
/// each row from the input vector to the output.
///
/// # Safety
///
/// Called by DuckDB. `input` / `output` are valid
/// `duckdb_vector` handles for the duration of the call.
unsafe extern "C" fn identity_cast_callback(
    _info: duckdb_function_info,
    count: idx_t,
    input: duckdb_vector,
    output: duckdb_vector,
) -> bool {
    let n = count as usize;
    if n == 0 {
        return true;
    }
    let in_data = duckdb_vector_get_data(input) as *const duckdb_string_t;
    let in_validity = duckdb_vector_get_validity(input);

    for i in 0..n {
        if !in_validity.is_null() && !duckdb_validity_row_is_valid(in_validity, i as idx_t) {
            duckdb_vector_ensure_validity_writable(output);
            let out_validity = duckdb_vector_get_validity(output);
            if !out_validity.is_null() {
                duckdb_validity_set_row_invalid(out_validity, i as idx_t);
            }
            continue;
        }
        let mut s_raw: duckdb_string_t = std::ptr::read(in_data.add(i));
        let len = ffi::duckdb_string_t_length(s_raw) as usize;
        let p = ffi::duckdb_string_t_data(&mut s_raw as *mut duckdb_string_t);
        duckdb_vector_assign_string_element_len(
            output,
            i as idx_t,
            p as *const c_char,
            len as idx_t,
        );
    }

    // Touch `count` to silence the unused warning on early-return paths.
    let _ = duckdb_data_chunk_get_size;
    true
}

// ----------------------------------------------------------------------
// Cast rewrites the shim advertises (for future functional-cast pass).
// ----------------------------------------------------------------------

// === extension: mobilitydb ===
// CAST(<castsourcekind::stringliteral> AS bitemporal_bool) → bitemporal_bool_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS bitemporal_float) → bitemporal_float_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS bitemporal_int) → bitemporal_int_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS bitemporal_text) → bitemporal_text_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS datespan) → datespan_from_text (hint: )
// CAST(<castsourcekind::stringliteral> AS datespanset) → datespanset_from_text (hint: )
// CAST(<castsourcekind::stringliteral> AS floatspan) → floatspan_from_text (hint: )
// CAST(<castsourcekind::stringliteral> AS floatspanset) → floatspanset_from_text (hint: )
// CAST(<castsourcekind::stringliteral> AS intspan) → intspan_from_text (hint: )
// CAST(<castsourcekind::stringliteral> AS intspanset) → intspanset_from_text (hint: )
// CAST(<castsourcekind::stringliteral> AS stbox) → stbox_from_text (hint: )
// CAST(<castsourcekind::stringliteral> AS stbox3d) → stbox3d_from_text (hint: )
// CAST(<castsourcekind::stringliteral> AS tbool) → tbool_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS tbool_sequence) → tbool_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS tbox) → tbox_from_text (hint: )
// CAST(<castsourcekind::stringliteral> AS tcbuffer) → tcbuffer_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS tcbuffer_sequence) → tcbuffer_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS textset) → textset_from_text (hint: )
// CAST(<castsourcekind::stringliteral> AS tfloat) → tfloat_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS tfloat_sequence) → tfloat_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS tgeogpoint) → tgeogpoint_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS tgeogpoint_sequence) → tgeogpoint_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS tgeompoint) → tgeompoint_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS tgeompoint3d) → tgeompoint3d_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS tgeompoint3d_sequence) → tgeompoint3d_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS tgeompoint_sequence) → tgeompoint_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS tint) → tint_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS tint_sequence) → tint_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS tnpoint) → tnpoint_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS tnpoint_sequence) → tnpoint_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS tpose) → tpose_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS tpose_sequence) → tpose_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS tstzspan) → tstzspan_from_text (hint: )
// CAST(<castsourcekind::stringliteral> AS tstzspanset) → tstzspanset_from_text (hint: )
// CAST(<castsourcekind::stringliteral> AS ttext) → ttext_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS ttext_sequence) → ttext_from_ewkt (hint: )
