// === GENERATED by ducklink-shim-codegen — do not edit by hand ===

//! CAST(x AS T) — DuckDB has cast hooks for USER types.
//!
//! ## Phase 4d — partially blocked
//!
//! For `source_kind == "any"` casts, DuckDB exposes
//! register_cast_function — but routing INTO it requires the
//! same private `Connection.db` we're blocked on for
//! aggregates (Phase 3c) and custom types (Phase 4b). Both
//! prerequisites would unblock this together.
//!
//! For `source_kind == "stringliteral"` and `"geographycolumn"`,
//! the rewrite is source-shape-driven (look at the expression
//! shape, not the type) — DuckDB's CAST hooks are type-driven,
//! so even when the API ships, these rewrites need to go to
//! the `ducklink-preprocess` crate instead.

use duckdb::{Connection, Result};

pub fn register_all(_conn: &Connection) -> Result<()> {
    Ok(())
}

// ----------------------------------------------------------------------
// Cast rewrites the shim advertises.
// ----------------------------------------------------------------------

// === extension: mobilitydb ===
// CAST(<castsourcekind::stringliteral> AS bitemporal_bool) → bitemporal_bool_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS bitemporal_float) → bitemporal_float_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS bitemporal_int) → bitemporal_int_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS bitemporal_text) → bitemporal_text_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS datespan) → datespan_from_text (hint: )
// CAST(<castsourcekind::stringliteral> AS datespanset) → datespanset_from_text (hint: )
// CAST(<castsourcekind::stringliteral> AS floatspan) → floatspan_from_text (hint: )
// CAST(<castsourcekind::stringliteral> AS floatspanset) → floatspanset_from_text (hint: )
// CAST(<castsourcekind::stringliteral> AS intspan) → intspan_from_text (hint: )
// CAST(<castsourcekind::stringliteral> AS intspanset) → intspanset_from_text (hint: )
// CAST(<castsourcekind::stringliteral> AS stbox) → stbox_from_text (hint: )
// CAST(<castsourcekind::stringliteral> AS stbox3d) → stbox3d_from_text (hint: )
// CAST(<castsourcekind::stringliteral> AS tbool) → tbool_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS tbool_sequence) → tbool_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS tbox) → tbox_from_text (hint: )
// CAST(<castsourcekind::stringliteral> AS tcbuffer) → tcbuffer_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS tcbuffer_sequence) → tcbuffer_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS textset) → textset_from_text (hint: )
// CAST(<castsourcekind::stringliteral> AS tfloat) → tfloat_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS tfloat_sequence) → tfloat_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS tgeogpoint) → tgeogpoint_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS tgeogpoint_sequence) → tgeogpoint_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS tgeompoint) → tgeompoint_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS tgeompoint3d) → tgeompoint3d_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS tgeompoint3d_sequence) → tgeompoint3d_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS tgeompoint_sequence) → tgeompoint_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS tint) → tint_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS tint_sequence) → tint_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS tnpoint) → tnpoint_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS tnpoint_sequence) → tnpoint_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS tpose) → tpose_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS tpose_sequence) → tpose_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS tstzspan) → tstzspan_from_text (hint: )
// CAST(<castsourcekind::stringliteral> AS tstzspanset) → tstzspanset_from_text (hint: )
// CAST(<castsourcekind::stringliteral> AS ttext) → ttext_from_ewkt (hint: )
// CAST(<castsourcekind::stringliteral> AS ttext_sequence) → ttext_from_ewkt (hint: )
