// === GENERATED by ducklink-shim-codegen — do not edit by hand ===
#![allow(dead_code, unused_imports)]

//! Generated DuckDB extension entry point.
//!
//! Load with:
//!   duckdb> INSTALL 'mobilitydb_duckdb_bridge' FROM '/path/to/dir';
//!   duckdb> LOAD 'mobilitydb_duckdb_bridge';
//!
//! Phase 1 (2026-06-24): scalar dispatch wired through
//! df-plugin-loader. ST_GeomFromText is fully functional; the
//! other categories (aggregates, UDTFs, window funcs, types,
//! operators, casts, preprocessors, system catalog, spatial
//! indexes) are scaffold-only — see per-module TODOs and
//! AGENTS.md for the phased plan.

pub mod aggregates;
pub mod casts;
pub mod operators;
pub mod preprocessors;
pub mod registry;
pub mod scalars;
pub mod spatial_indexes;
pub mod system_catalog;
pub mod table_functions;
pub mod types;
pub mod window_functions;

use std::error::Error;
use std::ffi::CString;

use libduckdb_sys as ffi;

/// DuckDB extension entry point. We hand-roll the C-ABI symbol
/// instead of using `#[duckdb_entrypoint_c_api]` so we can pull
/// the raw `duckdb_connection` out for the parts of the surface
/// (aggregates, custom types, casts) that duckdb-rs doesn't
/// wrap. The macro builds a `Connection` from
/// `duckdb_database` and discards everything else; we need the
/// raw pointer.
///
/// The composed shim wasm path comes from the
/// `MOBILITYDB_SHIM_WASM` env var so the bridge isn't pinned to
/// a build-time location (matches the host's runtime-loaded
/// model).
///
/// # Safety
///
/// Called by DuckDB on LOAD. `info` and `access` are valid for
/// the duration of this call.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn mobilitydb_duckdb_bridge_init_c_api(
    info: ffi::duckdb_extension_info,
    access: *const ffi::duckdb_extension_access,
) -> bool {
    match entrypoint_inner(info, access) {
        Ok(v) => v,
        Err(e) => {
            if let Some(set_error_fn) = (*access).set_error {
                if let Ok(cs) = CString::new(e.to_string()) {
                    set_error_fn(info, cs.as_ptr());
                }
            }
            false
        }
    }
}

unsafe fn entrypoint_inner(
    info: ffi::duckdb_extension_info,
    access: *const ffi::duckdb_extension_access,
) -> Result<bool, Box<dyn Error>> {
    // Step 1 — install function-pointer trampolines for the C
    // API version we built against (or refuse to load if the
    // running DuckDB is older).
    let have_api = ffi::duckdb_rs_extension_api_init(info, access, "v1.2.0")
        .map_err(|e| -> Box<dyn Error> { e.into() })?;
    if !have_api {
        return Ok(false);
    }

    // Step 2 — get the database handle DuckDB just opened.
    let get_database = (*access)
        .get_database
        .ok_or("get_database function pointer is null in duckdb_extension_access")?;
    let db_ptr = get_database(info);
    if db_ptr.is_null() {
        return Ok(false);
    }
    let db: ffi::duckdb_database = *db_ptr;

    // Step 3 — open a raw connection. We use this connection for
    // every registration call so types/aggregates/scalars all
    // land in the same catalog session. Leaked deliberately:
    // disconnecting here would invalidate registrations that
    // DuckDB holds by reference to this connection.
    let mut raw_con: ffi::duckdb_connection = std::ptr::null_mut();
    if ffi::duckdb_connect(db, &mut raw_con) != ffi::DuckDBSuccess {
        return Err("duckdb_connect failed".into());
    }

    // Step 4 — register custom types first (independent of the
    // shim; aliases-as-BLOB only need a duckdb_connection).
    // `CREATE TABLE t (g GEOMETRY)` works even if the shim
    // failed to load.
    types::register_all(raw_con);

    // Step 4b — register identity casts BLOB <-> alias so
    // INSERT INTO t (GEOMETRY) VALUES (ST_GeomFromText(...))
    // doesn't fail with "Unimplemented type for cast
    // (BLOB -> GEOMETRY)". Must run after types::register_all.
    casts::register_all(raw_con);

    // Step 5 — load the wasm shim.
    registry::load_shim().map_err(|e| -> Box<dyn Error> { format!("shim load: {e:#}").into() })?;

    // Step 6 — scalars via raw libduckdb-sys. Each scalar is
    // registered as a function SET (one entry per parameter-list
    // overload) through the C scalar-function API, with a single
    // GENERIC dispatcher that reads each argument by its declared
    // DataType and writes the return by its declared type. This
    // subsumes every (param-types -> return) shape the shim
    // publishes — no enumerated shape table, no BLOB fallback.
    scalars::register_all(raw_con);

    // Step 7 — aggregates via raw libduckdb-sys.
    aggregates::register_all(raw_con);

    // Step 8 — UDTFs via raw libduckdb-sys (DuckDB's VTab
    // bind/init hooks are static, so we dispatch dynamically by
    // name through the C table-function API — same pattern as
    // aggregates).
    table_functions::register_all(raw_con);

    // Step 9 — spatial indexes. The loadable C API can't register
    // a custom INDEX access method (no duckdb_register_index_type),
    // so `CREATE INDEX … USING <name>` remains unsupported (a
    // documented limitation). Instead the shim's tested
    // spatial-index build + query path is exposed as a build
    // AGGREGATE plus query TABLE FUNCTIONS — see spatial_indexes.rs.
    spatial_indexes::register_all(raw_con);

    Ok(true)
}
// Extensions loaded by this bridge:
//
//   - mobilitydb v0.1.0  (2130 scalars, 60 agg, 43 udtf, 0 window, 116 types, 32 ops, 36 casts, 1 preps, 0 catalog, 0 indexes)
