// === GENERATED by ducklink-shim-codegen — do not edit by hand ===

//! Operator handling.
//!
//! ## Phase 4d — same architectural blocker as sqlink
//! (2026-06-24)
//!
//! DuckDB's parser tokenises operators at compile time too.
//! Custom symbols like `&&&` or `<#>` are unrecognised tokens
//! — `SELECT g1 &&& g2` is a parse error before any function
//! dispatch could intervene. DuckDB DOES recognise some
//! symbols (`<<`, `>>`, etc.) and could in principle bind them
//! to scalar functions, but the registration API isn't exposed
//! from duckdb-rs (same Connection-internals problem).
//!
//! ## Where this work actually lives
//!
//! SQL-preprocessing concern, not extension concern. The
//! proper home is a separate `ducklink-preprocess` crate that:
//!
//!   - Parses SQL via sqlparser-rs (DuckDB dialect)
//!   - Rewrites operators: `g1 && g2` → `st_bboxintersects(g1, g2)`
//!   - Rewrites casts to user-types: same approach
//!   - Hands rewritten SQL to duckdb-rs's `prepare`/`execute`
//!
//! That crate can be generated from the same BridgePlan but
//! is a separate target.

use duckdb::{Connection, Result};

pub fn register_all(_conn: &Connection) -> Result<()> {
    Ok(())
}

// ----------------------------------------------------------------------
// Operators the shim advertises.
// ----------------------------------------------------------------------

// === extension: mobilitydb ===
// `&&` (lhs=Some(3012), rhs=Some(3012))  →  intspan_overlaps
// `&&` (lhs=Some(3013), rhs=Some(3013))  →  floatspan_overlaps
// `&&` (lhs=Some(3014), rhs=Some(3014))  →  datespan_overlaps
// `&&` (lhs=Some(3015), rhs=Some(3015))  →  temporal_overlaps
// `&&` (lhs=Some(3021), rhs=Some(3021))  →  intspanset_overlaps
// `&&` (lhs=Some(3022), rhs=Some(3022))  →  floatspanset_overlaps
// `&&` (lhs=Some(3023), rhs=Some(3023))  →  datespanset_overlaps
// `&&` (lhs=Some(3025), rhs=Some(3025))  →  stbox_overlaps
// `-|-` (lhs=Some(3015), rhs=Some(3015))  →  temporal_meets
// `<<` (lhs=Some(3015), rhs=Some(3015))  →  temporal_precedes
// `<<|` (lhs=Some(3015), rhs=Some(3015))  →  temporal_starts
// `<@` (lhs=Some(3015), rhs=Some(3015))  →  temporal_during
// `>>` (lhs=Some(3015), rhs=Some(3015))  →  temporal_follows
// `@` (lhs=Some(3001), rhs=None)  →  tfloat_value_at
// `@` (lhs=Some(3002), rhs=None)  →  tint_value_at
// `@` (lhs=Some(3003), rhs=None)  →  tbool_value_at
// `@` (lhs=Some(3004), rhs=None)  →  ttext_value_at
// `@>` (lhs=Some(3012), rhs=None)  →  intspan_contains
// `@>` (lhs=Some(3012), rhs=Some(3012))  →  intspan_contains_span
// `@>` (lhs=Some(3013), rhs=None)  →  floatspan_contains
// `@>` (lhs=Some(3013), rhs=Some(3013))  →  floatspan_contains_span
// `@>` (lhs=Some(3014), rhs=None)  →  datespan_contains
// `@>` (lhs=Some(3014), rhs=Some(3014))  →  datespan_contains_span
// `@>` (lhs=Some(3015), rhs=Some(3015))  →  temporal_contains
// `@>` (lhs=Some(3021), rhs=Some(3021))  →  intspanset_contains_span
// `@>` (lhs=Some(3022), rhs=Some(3022))  →  floatspanset_contains_span
// `@>` (lhs=Some(3023), rhs=Some(3023))  →  datespanset_contains_span
// `@>` (lhs=Some(3025), rhs=Some(3025))  →  stbox_contains
// `|>>` (lhs=Some(3015), rhs=Some(3015))  →  temporal_finishes
// `~=` (lhs=Some(3012), rhs=Some(3012))  →  intspan_adjacent
// `~=` (lhs=Some(3013), rhs=Some(3013))  →  floatspan_adjacent
// `~=` (lhs=Some(3014), rhs=Some(3014))  →  datespan_adjacent
