// === GENERATED by ducklink-shim-codegen — do not edit by hand ===

//! Token-level preprocessor patterns.
//!
//! ## Phase 4d — see operators.rs for the architectural picture.

use duckdb::{Connection, Result};

pub fn register_all(_conn: &Connection) -> Result<()> {
    Ok(())
}

// ----------------------------------------------------------------------
// Preprocessor patterns the shim advertises.
// ----------------------------------------------------------------------

// === extension: mobilitydb ===
// token `@` → __mdb_at__
