// === GENERATED by ducklink-shim-codegen — do not edit by hand ===
#![allow(dead_code, unused_imports)]

//! Spatial index build + query surface.
//!
//! ## What the loadable C API cannot do (documented limitation)
//!
//! DuckDB's stable loadable-extension C API (the only surface a
//! `--abi-type C_STRUCT` extension may call) has NO
//! `duckdb_register_index_type` (or equivalent). `CREATE INDEX …
//! USING <name>` resolves the access-method name against an
//! INTERNAL C++ registry a C-ABI extension cannot extend. So
//! `CREATE INDEX … USING rtree` / `… USING mobilitydb-strtree`
//! cannot be honoured by this bridge — that remains unsupported,
//! and DuckDB reports its own `Unknown index type`.
//!
//! ## What DOES work — the shim's tested build + query path
//!
//! The DataFission shim ships a complete, tested spatial-index
//! build + query path. The bridge's shim load
//! (`registry::load_shim` -> `RuntimeWasmExtension::register`)
//! installs the wasm-backed `SpatialIndexBuilder` into this
//! process's `datafission_index` registry under the aliases the
//! shim advertises. So `build_spatial_index(name, items)` routes
//! to the REAL shim R-tree / STRtree — no native reimplementation.
//!
//! We expose that through DuckDB as:
//!
//!   * a build AGGREGATE
//!       `<ext>_spatial_index_build(item_id BIGINT, geom_wkb BLOB)
//!         -> BIGINT`
//!     that accumulates (item_id, wkb) pairs, calls
//!     `build_spatial_index` at finalize, parks the resulting
//!     index in a session handle registry, and returns a u64
//!     HANDLE.
//!
//!   * query TABLE FUNCTIONS keyed by that handle:
//!       `<ext>_spatial_index_query_envelope(handle, min_x, min_y,
//!         max_x, max_y) -> (item_id BIGINT)`
//!       `<ext>_spatial_index_query_knn(handle, query_wkb, k)
//!         -> (item_id BIGINT)`            (if capabilities.knn)
//!       `<ext>_spatial_index_within_distance(handle, query_wkb,
//!         distance) -> (item_id BIGINT)`  (if within_distance_wkb)
//!
//! The build/query surface is `async`; the DuckDB callbacks are
//! sync, so calls are driven on a process-wide current-thread
//! tokio runtime via `block_on`.
//!
//! Everything here is interface-DB driven (the `spatial_indexes`
//! table + its `capabilities_json`): a future shim that declares a
//! spatial index gets this surface automatically.

use std::collections::HashMap;
use std::ffi::{c_char, c_void, CString};
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::Arc;

use once_cell::sync::OnceCell;
use parking_lot::Mutex;

use libduckdb_sys::{
    self as ffi, duckdb_aggregate_function_add_parameter, duckdb_aggregate_function_get_extra_info,
    duckdb_aggregate_function_set_error, duckdb_aggregate_function_set_extra_info,
    duckdb_aggregate_function_set_functions, duckdb_aggregate_function_set_name,
    duckdb_aggregate_function_set_return_type, duckdb_aggregate_state,
    duckdb_bind_add_result_column, duckdb_bind_get_extra_info, duckdb_bind_get_parameter,
    duckdb_bind_get_parameter_count, duckdb_bind_info, duckdb_bind_set_bind_data,
    duckdb_bind_set_error, duckdb_connection, duckdb_create_aggregate_function,
    duckdb_create_table_function, duckdb_data_chunk, duckdb_data_chunk_get_size,
    duckdb_data_chunk_get_vector, duckdb_data_chunk_set_size, duckdb_destroy_aggregate_function,
    duckdb_destroy_table_function, duckdb_function_get_bind_data, duckdb_function_get_init_data,
    duckdb_function_info, duckdb_function_set_error, duckdb_init_get_bind_data, duckdb_init_info,
    duckdb_init_set_init_data, duckdb_init_set_max_threads, duckdb_register_aggregate_function,
    duckdb_register_table_function, duckdb_string_t, duckdb_table_function_add_parameter,
    duckdb_table_function_set_bind, duckdb_table_function_set_extra_info,
    duckdb_table_function_set_function, duckdb_table_function_set_init,
    duckdb_table_function_set_name, duckdb_vector, idx_t, DuckDBSuccess,
};

use datafission_index::spatial::build_spatial_index;
use datafission_index::{Envelope, SpatialIndex};

// =====================================================================
// Async runtime + session handle registry.
// =====================================================================

/// Process-wide current-thread tokio runtime used to drive the
/// async build/query calls from the sync DuckDB callbacks. The
/// wasm-backed builder/index do no real awaiting internally, so a
/// current-thread runtime is sufficient.
fn runtime() -> &'static tokio::runtime::Runtime {
    static RT: OnceCell<tokio::runtime::Runtime> = OnceCell::new();
    RT.get_or_init(|| {
        tokio::runtime::Builder::new_current_thread()
            .build()
            .expect("build current-thread tokio runtime")
    })
}

/// block_on a future on the shared runtime.
fn block_on<F: std::future::Future>(fut: F) -> F::Output {
    runtime().block_on(fut)
}

/// Session handle registry: u64 handle -> built index. The index
/// is the loader-backed `Arc<dyn SpatialIndex>` returned by
/// `build_spatial_index`, i.e. the real shim R-tree.
fn handles() -> &'static Mutex<HashMap<u64, Arc<dyn SpatialIndex>>> {
    static H: OnceCell<Mutex<HashMap<u64, Arc<dyn SpatialIndex>>>> = OnceCell::new();
    H.get_or_init(|| Mutex::new(HashMap::new()))
}

static NEXT_HANDLE: AtomicU64 = AtomicU64::new(1);

fn store_index(idx: Arc<dyn SpatialIndex>) -> u64 {
    let h = NEXT_HANDLE.fetch_add(1, Ordering::Relaxed);
    handles().lock().insert(h, idx);
    h
}

fn get_index(handle: u64) -> Option<Arc<dyn SpatialIndex>> {
    handles().lock().get(&handle).cloned()
}

/// Register the spatial-index build aggregate + query table
/// functions for every extension that declares a spatial index.
///
/// # Safety
///
/// `conn` must be a valid `duckdb_connection` for the duration of
/// this call.
pub unsafe fn register_all(conn: duckdb_connection) {
    register_build_aggregate(conn, "mobilitydb_spatial_index_build", "mobilitydb-strtree");
    register_query_tf(
        conn,
        "mobilitydb_spatial_index_query_envelope",
        QueryKind::Envelope,
    );
    register_query_tf(conn, "mobilitydb_spatial_index_query_knn", QueryKind::Knn);
    register_query_tf(
        conn,
        "mobilitydb_spatial_index_within_distance",
        QueryKind::WithinDistance,
    );
}

// =====================================================================
// Build AGGREGATE: (item_id BIGINT, geom_wkb BLOB) -> BIGINT handle.
//
// Accumulates (item_id, wkb) pairs; at finalize calls
// build_spatial_index(name, items) and returns a session handle.
// =====================================================================

/// Per-registration state stashed on the aggregate.
struct BuildExtraInfo {
    /// The builder alias passed to build_spatial_index (the shim's
    /// primary spatial-index name).
    index_name: String,
}

/// Per-group accumulator: the collected (item_id, wkb) pairs.
struct BuildState {
    items: Vec<(u64, Vec<u8>)>,
}

type BuildStatePtr = *mut BuildState;

unsafe fn register_build_aggregate(conn: duckdb_connection, sql_name: &str, index_name: &str) {
    let agg = duckdb_create_aggregate_function();
    let name_cs = match CString::new(sql_name) {
        Ok(c) => c,
        Err(_) => {
            eprintln!("[shim-spatial-index] name contains NUL: `{sql_name}`");
            duckdb_destroy_aggregate_function(&mut { agg });
            return;
        }
    };
    duckdb_aggregate_function_set_name(agg, name_cs.as_ptr());

    // (BIGINT item_id, BLOB geom_wkb) -> BIGINT handle.
    let id_lt = ffi::duckdb_create_logical_type(ffi::DUCKDB_TYPE_DUCKDB_TYPE_BIGINT);
    duckdb_aggregate_function_add_parameter(agg, id_lt);
    let wkb_lt = ffi::duckdb_create_logical_type(ffi::DUCKDB_TYPE_DUCKDB_TYPE_BLOB);
    duckdb_aggregate_function_add_parameter(agg, wkb_lt);
    let ret_lt = ffi::duckdb_create_logical_type(ffi::DUCKDB_TYPE_DUCKDB_TYPE_BIGINT);
    duckdb_aggregate_function_set_return_type(agg, ret_lt);
    let mut d = id_lt;
    ffi::duckdb_destroy_logical_type(&mut d);
    let mut d = wkb_lt;
    ffi::duckdb_destroy_logical_type(&mut d);
    let mut d = ret_lt;
    ffi::duckdb_destroy_logical_type(&mut d);

    duckdb_aggregate_function_set_functions(
        agg,
        Some(build_state_size),
        Some(build_state_init),
        Some(build_update),
        Some(build_combine),
        Some(build_finalize),
    );
    ffi::duckdb_aggregate_function_set_destructor(agg, Some(build_state_destroy));

    let extra = Box::into_raw(Box::new(BuildExtraInfo {
        index_name: index_name.to_string(),
    }));
    duckdb_aggregate_function_set_extra_info(agg, extra as *mut c_void, Some(drop_build_extra));

    let rc = duckdb_register_aggregate_function(conn, agg);
    duckdb_destroy_aggregate_function(&mut { agg });
    if rc != DuckDBSuccess {
        eprintln!("[shim-spatial-index] could not register build aggregate `{sql_name}` (rc={rc})");
    }
}

unsafe extern "C" fn build_state_size(_info: duckdb_function_info) -> idx_t {
    std::mem::size_of::<BuildStatePtr>() as idx_t
}

unsafe extern "C" fn build_state_init(_info: duckdb_function_info, state: duckdb_aggregate_state) {
    let boxed = Box::into_raw(Box::new(BuildState { items: Vec::new() }));
    std::ptr::write(state as *mut BuildStatePtr, boxed);
}

unsafe extern "C" fn build_state_destroy(states: *mut duckdb_aggregate_state, count: idx_t) {
    for i in 0..count as usize {
        let slot = ptr_read_state_slot(states, i);
        if !slot.is_null() {
            drop(Box::from_raw(slot));
        }
    }
}

/// `states` is an array of state pointers (slots). Read the i-th
/// slot, then read the BuildStatePtr stored in it.
unsafe fn ptr_read_state_slot(states: *mut duckdb_aggregate_state, idx: usize) -> BuildStatePtr {
    let slot = std::ptr::read(states.add(idx)) as *mut BuildStatePtr;
    std::ptr::read(slot)
}

unsafe extern "C" fn build_update(
    info: duckdb_function_info,
    input: duckdb_data_chunk,
    states: *mut duckdb_aggregate_state,
) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let n = duckdb_data_chunk_get_size(input) as usize;
        let id_vec = duckdb_data_chunk_get_vector(input, 0);
        let wkb_vec = duckdb_data_chunk_get_vector(input, 1);
        let ids = ffi::duckdb_vector_get_data(id_vec) as *const i64;
        for i in 0..n {
            if si_vector_row_is_null(id_vec, i) || si_vector_row_is_null(wkb_vec, i) {
                continue;
            }
            let item_id = std::ptr::read(ids.add(i)) as u64;
            let wkb = si_read_blob(wkb_vec, i);
            let acc = ptr_read_state_slot(states, i);
            if !acc.is_null() {
                (*acc).items.push((item_id, wkb));
            }
        }
    }))
    .map_err(|_| si_agg_err(info, "panic in spatial-index build update"));
}

unsafe extern "C" fn build_combine(
    _info: duckdb_function_info,
    source: *mut duckdb_aggregate_state,
    target: *mut duckdb_aggregate_state,
    count: idx_t,
) {
    for i in 0..count as usize {
        let src = ptr_read_state_slot(source, i);
        let tgt = ptr_read_state_slot(target, i);
        if !src.is_null() && !tgt.is_null() {
            let drained: Vec<(u64, Vec<u8>)> = std::mem::take(&mut (*src).items);
            (*tgt).items.extend(drained);
        }
    }
}

unsafe extern "C" fn build_finalize(
    info: duckdb_function_info,
    source: *mut duckdb_aggregate_state,
    result: duckdb_vector,
    count: idx_t,
    offset: idx_t,
) {
    let extra = &*(duckdb_aggregate_function_get_extra_info(info) as *const BuildExtraInfo);
    let out = ffi::duckdb_vector_get_data(result) as *mut i64;
    for i in 0..count as usize {
        let acc = ptr_read_state_slot(source, i);
        if acc.is_null() {
            si_set_vector_null(result, offset as usize + i);
            continue;
        }
        let items = std::mem::take(&mut (*acc).items);
        let res = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
            block_on(build_spatial_index(&extra.index_name, items))
        }));
        match res {
            Ok(Ok(index)) => {
                let handle = store_index(index);
                std::ptr::write(out.add(offset as usize + i), handle as i64);
            }
            Ok(Err(e)) => {
                si_agg_err(info, &format!("build_spatial_index failed: {e:?}"));
                si_set_vector_null(result, offset as usize + i);
            }
            Err(_) => {
                si_agg_err(info, "panic in build_spatial_index");
                si_set_vector_null(result, offset as usize + i);
            }
        }
    }
}

// =====================================================================
// Query TABLE FUNCTIONS keyed by a handle.
//
// envelope: (handle BIGINT, min_x, min_y, max_x, max_y DOUBLE)
// knn:      (handle BIGINT, query_wkb BLOB, k INTEGER)
// within:   (handle BIGINT, query_wkb BLOB, distance DOUBLE)
// each yields one BIGINT `item_id` per hit.
// =====================================================================

#[derive(Clone, Copy)]
enum QueryKind {
    Envelope,
    Knn,
    WithinDistance,
}

struct QueryExtra {
    kind: QueryKind,
}

struct QueryBind {
    kind: QueryKind,
    handle: u64,
    // Envelope args (or the derived query-point envelope for within).
    env: Envelope,
    // knn / within payloads.
    wkb: Vec<u8>,
    k: usize,
    distance: f64,
}

#[repr(C)]
struct QueryInit {
    tag: u8,
    hits: Vec<u64>,
    pos: Mutex<usize>,
}

const SI_OK_TAG: u8 = 0x0C;
const SI_ERR_TAG: u8 = 0xE5;

#[repr(C)]
struct QueryInitErr {
    tag: u8,
    msg: String,
}

unsafe fn register_query_tf(conn: duckdb_connection, sql_name: &str, kind: QueryKind) {
    let tf = duckdb_create_table_function();
    let name_cs = match CString::new(sql_name) {
        Ok(c) => c,
        Err(_) => {
            eprintln!("[shim-spatial-index] name contains NUL: `{sql_name}`");
            duckdb_destroy_table_function(&mut { tf });
            return;
        }
    };
    duckdb_table_function_set_name(tf, name_cs.as_ptr());

    // Declare positional parameters by kind.
    let add = |id: ffi::duckdb_type| {
        let lt = ffi::duckdb_create_logical_type(id);
        duckdb_table_function_add_parameter(tf, lt);
        let mut d = lt;
        ffi::duckdb_destroy_logical_type(&mut d);
    };
    add(ffi::DUCKDB_TYPE_DUCKDB_TYPE_BIGINT); // handle
    match kind {
        QueryKind::Envelope => {
            add(ffi::DUCKDB_TYPE_DUCKDB_TYPE_DOUBLE); // min_x
            add(ffi::DUCKDB_TYPE_DUCKDB_TYPE_DOUBLE); // min_y
            add(ffi::DUCKDB_TYPE_DUCKDB_TYPE_DOUBLE); // max_x
            add(ffi::DUCKDB_TYPE_DUCKDB_TYPE_DOUBLE); // max_y
        }
        QueryKind::Knn => {
            add(ffi::DUCKDB_TYPE_DUCKDB_TYPE_BLOB); // query_wkb
            add(ffi::DUCKDB_TYPE_DUCKDB_TYPE_INTEGER); // k
        }
        QueryKind::WithinDistance => {
            add(ffi::DUCKDB_TYPE_DUCKDB_TYPE_BLOB); // query_wkb
            add(ffi::DUCKDB_TYPE_DUCKDB_TYPE_DOUBLE); // distance
        }
    }

    duckdb_table_function_set_bind(tf, Some(query_bind));
    duckdb_table_function_set_init(tf, Some(query_init));
    duckdb_table_function_set_function(tf, Some(query_func));

    let extra = Box::into_raw(Box::new(QueryExtra { kind }));
    duckdb_table_function_set_extra_info(tf, extra as *mut c_void, Some(drop_query_extra));

    let rc = duckdb_register_table_function(conn, tf);
    duckdb_destroy_table_function(&mut { tf });
    if rc != DuckDBSuccess {
        eprintln!("[shim-spatial-index] could not register query tf `{sql_name}` (rc={rc})");
    }
}

unsafe extern "C" fn query_bind(info: duckdb_bind_info) {
    match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| query_bind_inner(info))) {
        Ok(Ok(())) => {}
        Ok(Err(msg)) => si_bind_err(info, &msg),
        Err(_) => si_bind_err(info, "panic in spatial-index query bind"),
    }
}

unsafe fn query_bind_inner(info: duckdb_bind_info) -> Result<(), String> {
    let extra = &*(duckdb_bind_get_extra_info(info) as *const QueryExtra);
    let kind = extra.kind;
    let nparams = duckdb_bind_get_parameter_count(info) as usize;

    let get_i64 = |i: usize| -> i64 {
        let v = duckdb_bind_get_parameter(info, i as idx_t);
        let r = ffi::duckdb_get_int64(v);
        let mut vv = v;
        ffi::duckdb_destroy_value(&mut vv);
        r
    };
    let get_i32 = |i: usize| -> i32 {
        let v = duckdb_bind_get_parameter(info, i as idx_t);
        let r = ffi::duckdb_get_int32(v);
        let mut vv = v;
        ffi::duckdb_destroy_value(&mut vv);
        r
    };
    let get_f64 = |i: usize| -> f64 {
        let v = duckdb_bind_get_parameter(info, i as idx_t);
        let r = ffi::duckdb_get_double(v);
        let mut vv = v;
        ffi::duckdb_destroy_value(&mut vv);
        r
    };
    let get_blob = |i: usize| -> Vec<u8> {
        let v = duckdb_bind_get_parameter(info, i as idx_t);
        let b = ffi::duckdb_get_blob(v);
        let bytes = if b.data.is_null() || b.size == 0 {
            Vec::new()
        } else {
            std::slice::from_raw_parts(b.data as *const u8, b.size as usize).to_vec()
        };
        let mut vv = v;
        ffi::duckdb_destroy_value(&mut vv);
        bytes
    };

    if nparams == 0 {
        return Err("spatial-index query: missing handle argument".into());
    }
    let handle = get_i64(0) as u64;

    let mut bind = QueryBind {
        kind,
        handle,
        env: Envelope::new(0.0, 0.0, 0.0, 0.0),
        wkb: Vec::new(),
        k: 0,
        distance: 0.0,
    };
    match kind {
        QueryKind::Envelope => {
            if nparams < 5 {
                return Err("query_envelope: expected (handle, min_x, min_y, max_x, max_y)".into());
            }
            bind.env = Envelope::new(get_f64(1), get_f64(2), get_f64(3), get_f64(4));
        }
        QueryKind::Knn => {
            if nparams < 3 {
                return Err("query_knn: expected (handle, query_wkb, k)".into());
            }
            bind.wkb = get_blob(1);
            bind.k = get_i32(2).max(0) as usize;
        }
        QueryKind::WithinDistance => {
            if nparams < 3 {
                return Err("within_distance: expected (handle, query_wkb, distance)".into());
            }
            bind.wkb = get_blob(1);
            bind.distance = get_f64(2);
            // Derive the query-point envelope from the WKB so we can
            // call query_within_distance_envelope.
            bind.env = wkb_point_envelope(&bind.wkb)
                .ok_or_else(|| "within_distance: query_wkb is not a parseable POINT".to_string())?;
        }
    }

    // Declare the single output column: item_id BIGINT.
    let col = CString::new("item_id").unwrap();
    let lt = ffi::duckdb_create_logical_type(ffi::DUCKDB_TYPE_DUCKDB_TYPE_BIGINT);
    duckdb_bind_add_result_column(info, col.as_ptr(), lt);
    let mut d = lt;
    ffi::duckdb_destroy_logical_type(&mut d);

    let boxed = Box::into_raw(Box::new(bind));
    duckdb_bind_set_bind_data(info, boxed as *mut c_void, Some(drop_query_bind));
    Ok(())
}

unsafe extern "C" fn query_init(info: duckdb_init_info) {
    let res = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| query_init_inner(info)));
    match res {
        Ok(Ok(())) => {}
        Ok(Err(msg)) => install_query_err(info, msg),
        Err(_) => install_query_err(info, "panic in spatial-index query init".into()),
    }
}

unsafe fn query_init_inner(info: duckdb_init_info) -> Result<(), String> {
    let bind = &*(duckdb_init_get_bind_data(info) as *const QueryBind);
    let index = get_index(bind.handle)
        .ok_or_else(|| format!("spatial-index handle {} not found", bind.handle))?;

    let hits: Vec<u64> = match bind.kind {
        QueryKind::Envelope => block_on(index.query_envelope(&bind.env))
            .map_err(|e| format!("query_envelope: {e:?}"))?,
        QueryKind::Knn => {
            block_on(index.query_knn(&bind.wkb, bind.k)).map_err(|e| format!("query_knn: {e:?}"))?
        }
        QueryKind::WithinDistance => {
            block_on(index.query_within_distance_envelope(&bind.env, bind.distance))
                .map_err(|e| format!("within_distance: {e:?}"))?
        }
    };

    duckdb_init_set_max_threads(info, 1);
    let init = Box::into_raw(Box::new(QueryInit {
        tag: SI_OK_TAG,
        hits,
        pos: Mutex::new(0),
    }));
    duckdb_init_set_init_data(info, init as *mut c_void, Some(drop_query_init));
    Ok(())
}

unsafe fn install_query_err(info: duckdb_init_info, msg: String) {
    let err = Box::into_raw(Box::new(QueryInitErr {
        tag: SI_ERR_TAG,
        msg,
    }));
    duckdb_init_set_init_data(info, err as *mut c_void, Some(drop_query_init_err));
}

unsafe extern "C" fn query_func(info: duckdb_function_info, output: duckdb_data_chunk) {
    match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        query_func_inner(info, output)
    })) {
        Ok(Ok(())) => {}
        Ok(Err(msg)) => si_func_err(info, &msg),
        Err(_) => si_func_err(info, "panic in spatial-index query scan"),
    }
}

unsafe fn query_func_inner(
    info: duckdb_function_info,
    output: duckdb_data_chunk,
) -> Result<(), String> {
    let raw = duckdb_function_get_init_data(info);
    if raw.is_null() {
        duckdb_data_chunk_set_size(output, 0);
        return Ok(());
    }
    let tag = *(raw as *const u8);
    if tag == SI_ERR_TAG {
        let err = &*(raw as *const QueryInitErr);
        return Err(err.msg.clone());
    }
    let init = &*(raw as *const QueryInit);

    let cap = ffi::duckdb_vector_size() as usize;
    let vec = duckdb_data_chunk_get_vector(output, 0);
    let out = ffi::duckdb_vector_get_data(vec) as *mut i64;

    let mut pos = init.pos.lock();
    let mut produced = 0usize;
    while produced < cap && *pos < init.hits.len() {
        std::ptr::write(out.add(produced), init.hits[*pos] as i64);
        *pos += 1;
        produced += 1;
    }
    duckdb_data_chunk_set_size(output, produced as idx_t);
    Ok(())
}

// =====================================================================
// Minimal WKB POINT -> point-envelope parser (for within_distance).
//
// Supports a 2D POINT in WKB/EWKB: 1-byte byte-order, 4-byte type
// (low bits = 1 for POINT; EWKB SRID flag tolerated), then X,Y as
// 8-byte doubles. Returns a degenerate point envelope.
// =====================================================================

unsafe fn wkb_point_envelope(bytes: &[u8]) -> Option<Envelope> {
    // Not unsafe-dependent, but kept in the unsafe block region for
    // locality; pure byte parsing.
    if bytes.len() < 21 {
        return None;
    }
    let le = bytes[0] == 1;
    let rd_u32 = |o: usize| -> u32 {
        let b = [bytes[o], bytes[o + 1], bytes[o + 2], bytes[o + 3]];
        if le {
            u32::from_le_bytes(b)
        } else {
            u32::from_be_bytes(b)
        }
    };
    let rd_f64 = |o: usize| -> f64 {
        let mut b = [0u8; 8];
        b.copy_from_slice(&bytes[o..o + 8]);
        if le {
            f64::from_le_bytes(b)
        } else {
            f64::from_be_bytes(b)
        }
    };
    let geom_type = rd_u32(1);
    // Low 16 bits hold the base type; POINT == 1. (EWKB packs SRID /
    // Z / M flags in the high bits, which we ignore for a 2D point.)
    if (geom_type & 0x000000ff) != 1 {
        return None;
    }
    // EWKB with SRID flag (0x20000000) inserts a 4-byte SRID before
    // the coordinates.
    let coord_off = if (geom_type & 0x20000000) != 0 { 9 } else { 5 };
    if bytes.len() < coord_off + 16 {
        return None;
    }
    let x = rd_f64(coord_off);
    let y = rd_f64(coord_off + 8);
    Some(Envelope::point(x, y))
}

// =====================================================================
// Shared helpers (prefixed `si_` to avoid clashing with other
// modules emitted into the same crate).
// =====================================================================

unsafe fn si_read_blob(vec: duckdb_vector, row: usize) -> Vec<u8> {
    let data = ffi::duckdb_vector_get_data(vec) as *const duckdb_string_t;
    let s = &*data.add(row);
    let len = s.value.inlined.length as usize;
    if len <= 12 {
        let inl = &s.value.inlined.inlined;
        std::slice::from_raw_parts(inl.as_ptr() as *const u8, len).to_vec()
    } else {
        std::slice::from_raw_parts(s.value.pointer.ptr as *const u8, len).to_vec()
    }
}

unsafe fn si_vector_row_is_null(vec: duckdb_vector, row: usize) -> bool {
    let validity = ffi::duckdb_vector_get_validity(vec);
    if validity.is_null() {
        return false;
    }
    !ffi::duckdb_validity_row_is_valid(validity, row as idx_t)
}

unsafe fn si_set_vector_null(vec: duckdb_vector, row: usize) {
    ffi::duckdb_vector_ensure_validity_writable(vec);
    let validity = ffi::duckdb_vector_get_validity(vec);
    if !validity.is_null() {
        ffi::duckdb_validity_set_row_invalid(validity, row as idx_t);
    }
}

unsafe fn si_agg_err(info: duckdb_function_info, msg: &str) {
    if let Ok(cs) = CString::new(msg) {
        duckdb_aggregate_function_set_error(info, cs.as_ptr() as *const c_char);
    }
}

unsafe fn si_bind_err(info: duckdb_bind_info, msg: &str) {
    if let Ok(cs) = CString::new(msg) {
        duckdb_bind_set_error(info, cs.as_ptr() as *const c_char);
    }
}

unsafe fn si_func_err(info: duckdb_function_info, msg: &str) {
    if let Ok(cs) = CString::new(msg) {
        duckdb_function_set_error(info, cs.as_ptr() as *const c_char);
    }
}

unsafe extern "C" fn drop_build_extra(ptr: *mut c_void) {
    if !ptr.is_null() {
        drop(Box::from_raw(ptr as *mut BuildExtraInfo));
    }
}

unsafe extern "C" fn drop_query_extra(ptr: *mut c_void) {
    if !ptr.is_null() {
        drop(Box::from_raw(ptr as *mut QueryExtra));
    }
}

unsafe extern "C" fn drop_query_bind(ptr: *mut c_void) {
    if !ptr.is_null() {
        drop(Box::from_raw(ptr as *mut QueryBind));
    }
}

unsafe extern "C" fn drop_query_init(ptr: *mut c_void) {
    if !ptr.is_null() {
        drop(Box::from_raw(ptr as *mut QueryInit));
    }
}

unsafe extern "C" fn drop_query_init_err(ptr: *mut c_void) {
    if !ptr.is_null() {
        drop(Box::from_raw(ptr as *mut QueryInitErr));
    }
}

// ----------------------------------------------------------------------
// Spatial indexes the shim advertises.
// ----------------------------------------------------------------------

// === extension: mobilitydb ===
// index `type_id=4001` type_id=4001 caps=(none)
// index `mobilitydb-strtree` type_id=0 caps={"knn":true,"update_after_build":false,"within_distance":false,"within_distance_wkb":true}
// index `trajbbox` type_id=0 caps={"knn":true,"update_after_build":false,"within_distance":false,"within_distance_wkb":true}
