// === GENERATED by ducklink-shim-codegen — do not edit by hand ===

//! Spatial index registration.
//!
//! DuckDB has built-in ART (B-tree-ish) indexes plus an
//! `IndexExtensionEntry` hook for extension-defined index
//! kinds (used by the spatial extension's R-tree). Map each
//! shim spatial-index `type_id` to a DuckDB index extension
//! entry; SQL `CREATE INDEX … USING <name>` resolves through
//! the catalog.
//!
//! Older DuckDB versions without `IndexExtensionEntry` fall
//! back to registering an index-aware UDTF that participates
//! in the optimizer's predicate pushdown via the bind
//! callback.

// index `mobilitydb-strtree` type_id=0
// index `trajbbox` type_id=0
// index `type_id=4001` type_id=4001

// TODO: register IndexExtensionEntry per shim index,
//       or fall back to UDTF + pushdown.
