// === GENERATED by ducklink-shim-codegen — do not edit by hand ===

//! Table-function registration.
//!
//! ## Phase 4c — SCAFFOLDED (2026-06-24)
//!
//! Unlike aggregates (Phase 3c) and custom types (Phase 4b),
//! DuckDB's TableFunction API IS exposed in duckdb-rs via
//! the `VTab` trait. The `hello-ext` example
//! (`~/.cargo/registry/.../duckdb-1.x/examples/hello-ext/main.rs`)
//! shows the canonical pattern: bind/init/func callbacks +
//! `con.register_table_function::<HelloVTab>("hello")`.
//!
//! Architecture for shipping this
//!
//!   1. Define one concrete `ShimVTab` type with a BindData
//!      that holds Arc<dyn TableFunctionDef> + the parameter
//!      values from the SQL call.
//!
//!   2. `bind` reads SQL params via `bind.get_parameter(i)`,
//!      builds the output column schema from
//!      `def.output_schema(...)`.
//!
//!   3. `init` creates a per-query InitData holding
//!      `Box<dyn TableFunctionIterator>` from
//!      `def.execute(&function_values)`.
//!
//!   4. `func` calls `iter.next_row()` repeatedly to fill the
//!      output DataChunk; sets output length when chunk full
//!      or iter exhausted.
//!
//! Same blocker as Phase 3c/4b — the way duckdb-rs threads
//! state through bind/init/func means each shim UDTF needs
//! its own per-name VTab struct (or unsafe shared state).
//! With 7 PostGIS UDTFs and 2-3 ducks of unsafe code per
//! per-UDTF impl, this is ~400 LOC that warrants its own
//! session.

use duckdb::{Connection, Result};

/// Phase-4c no-op. The shim's UDTFs are captured in the
/// registry; the day someone writes the ShimVTab adapter,
/// this becomes a loop over registry::all_table_functions().
pub fn register_all(_conn: &Connection) -> Result<()> {
    Ok(())
}

// ----------------------------------------------------------------------
// UDTFs the shim publishes.
// ----------------------------------------------------------------------

// === extension: mobilitydb ===
// udtf `as_of_join_bool` (arity=2)
// udtf `as_of_join_float` (arity=2)
// udtf `as_of_join_int` (arity=2)
// udtf `as_of_join_text` (arity=2)
// udtf `interval_tree_query_overlapping` (arity=3)
// udtf `interval_tree_query_point` (arity=2)
// udtf `kdtree_xy_nearest_k` (arity=4)
// udtf `kdtree_xy_within` (arity=4)
// udtf `kdtree_xyz_nearest_k` (arity=5)
// udtf `kdtree_xyz_within` (arity=5)
// udtf `nearest_join_bool` (arity=2)
// udtf `nearest_join_float` (arity=2)
// udtf `nearest_join_int` (arity=2)
// udtf `nearest_join_text` (arity=2)
// udtf `octree_query_box` (arity=7)
// udtf `octree_query_sphere` (arity=5)
// udtf `quadtree_query_box` (arity=5)
// udtf `sequence_json` (arity=1)
// udtf `spatial_index_find_in_envelope` (arity=5)
// udtf `spatial_index_find_within_distance` (arity=4)
// udtf `spatial_index_nearest` (arity=3)
//   aliases: stindex_nearest
// udtf `spatial_index_nearest_k` (arity=4)
//   aliases: stindex_nearest_k
// udtf `stindex_find_in_period` (arity=3)
// udtf `stindex_find_in_spatial` (arity=5)
// udtf `stindex_find_in_stbox` (arity=2)
// udtf `tcbuffer_to_rows` (arity=1)
// udtf `temporal_index_find_after` (arity=2)
// udtf `temporal_index_find_at` (arity=2)
// udtf `temporal_index_find_before` (arity=2)
// udtf `temporal_index_find_in_range` (arity=3)
// udtf `temporal_index_find_overlapping` (arity=3)
// udtf `temporal_join_bool` (arity=2)
// udtf `temporal_join_float` (arity=2)
// udtf `temporal_join_int` (arity=2)
// udtf `temporal_join_text` (arity=2)
// udtf `tfloat_time_split` (arity=3)
// udtf `tfloat_value_split` (arity=3)
// udtf `tgeogpoint_to_rows` (arity=1)
// udtf `tgeompoint3d_to_rows` (arity=1)
// udtf `tgeompoint_to_rows` (arity=1)
// udtf `tint_time_split` (arity=3)
// udtf `tint_value_split` (arity=3)
// udtf `tpose_to_rows` (arity=1)
