// === GENERATED by ducklink-shim-codegen — do not edit by hand ===

//! Custom column types — alias BLOB as GEOMETRY, GEOGRAPHY, …
//!
//! Each shim type is registered with DuckDB as an alias for
//! `BLOB`. After registration `CREATE TABLE t (g GEOMETRY)`
//! shows `GEOMETRY` in the schema; storage and the function
//! ABI stay BLOB so existing `ScalarFunctionSignature::exact`
//! signatures keep working unchanged.
//!
//! For each registered type name we call:
//!
//!     handle = duckdb_create_logical_type(DUCKDB_TYPE_BLOB)
//!     duckdb_logical_type_set_alias(handle, "GEOMETRY")
//!     duckdb_register_logical_type(con, handle, NULL)
//!     duckdb_destroy_logical_type(handle)
//!
//! `duckdb_create_type_info` is reserved-for-future-use per
//! upstream comments — we pass NULL. On a name clash with an
//! existing type DuckDB returns DuckDBError; we log+continue
//! to match the policy aggregates_rs uses for scalar/aggregate
//! collisions.

use libduckdb_sys as ffi;
use std::ffi::CString;

/// Register every shim-published custom type as a BLOB alias.
///
/// # Safety
///
/// `con` must be a valid `duckdb_connection` for the duration
/// of this call.
pub unsafe fn register_all(con: ffi::duckdb_connection) {
    if con.is_null() {
        return;
    }
    register_type(con, "BITEMPORAL_BOOL");
    register_type(con, "BITEMPORAL_FLOAT");
    register_type(con, "BITEMPORAL_INT");
    register_type(con, "BITEMPORAL_TEXT");
    register_type(con, "DATESET");
    register_type(con, "DATESPAN");
    register_type(con, "DATESPANSET");
    register_type(con, "FLOATSET");
    register_type(con, "FLOATSPAN");
    register_type(con, "FLOATSPANSET");
    register_type(con, "INTSET");
    register_type(con, "INTSPAN");
    register_type(con, "INTSPANSET");
    register_type(con, "STBOX");
    register_type(con, "STBOX3D");
    register_type(con, "TBOOL_SEQUENCE");
    register_type(con, "TBOX");
    register_type(con, "TCBUFFER_SEQUENCE");
    register_type(con, "TEXTSET");
    register_type(con, "TFLOAT_SEQUENCE");
    register_type(con, "TGEOGPOINT_SEQUENCE");
    register_type(con, "TGEOMETRY_SEQUENCE");
    register_type(con, "TGEOMPOINT3D_SEQUENCE");
    register_type(con, "TGEOMPOINT_SEQUENCE");
    register_type(con, "TINT_SEQUENCE");
    register_type(con, "TNPOINT_SEQUENCE");
    register_type(con, "TPOSE_SEQUENCE");
    register_type(con, "TSTZSET");
    register_type(con, "TSTZSPAN");
    register_type(con, "TSTZSPANSET");
    register_type(con, "TTEXT_SEQUENCE");
}

unsafe fn register_type(con: ffi::duckdb_connection, name: &str) {
    let handle = ffi::duckdb_create_logical_type(ffi::DUCKDB_TYPE_DUCKDB_TYPE_BLOB);
    if handle.is_null() {
        eprintln!("[shim-types] could not create logical type for {name}");
        return;
    }
    let c_name = match CString::new(name) {
        Ok(c) => c,
        Err(_) => {
            eprintln!("[shim-types] type name contains NUL: {name}");
            let mut h = handle;
            ffi::duckdb_destroy_logical_type(&mut h);
            return;
        }
    };
    ffi::duckdb_logical_type_set_alias(handle, c_name.as_ptr());
    let rc = ffi::duckdb_register_logical_type(con, handle, std::ptr::null_mut());
    if rc != ffi::DuckDBSuccess {
        eprintln!(
            "[shim-types] could not register type {name} (rc={rc}) — \
             likely a name clash with an existing type"
        );
    }
    let mut h = handle;
    ffi::duckdb_destroy_logical_type(&mut h);
}

// ----------------------------------------------------------------------
// Column types the shim publishes.
// ----------------------------------------------------------------------

// === extension: mobilitydb ===
// type_id= 3001 name=TFLOAT_SEQUENCE          size=  -1  cast_from=[]  cast_to=[]
// type_id= 3002 name=TINT_SEQUENCE            size=  -1  cast_from=[]  cast_to=[]
// type_id= 3003 name=TBOOL_SEQUENCE           size=  -1  cast_from=[]  cast_to=[]
// type_id= 3004 name=TTEXT_SEQUENCE           size=  -1  cast_from=[]  cast_to=[]
// type_id= 3005 name=TGEOMPOINT_SEQUENCE      size=  -1  cast_from=[]  cast_to=[]
// type_id= 3006 name=TGEOGPOINT_SEQUENCE      size=  -1  cast_from=[]  cast_to=[]
// type_id= 3007 name=TGEOMPOINT3D_SEQUENCE    size=  -1  cast_from=[]  cast_to=[]
// type_id= 3008 name=TGEOMETRY_SEQUENCE       size=  -1  cast_from=[]  cast_to=[]
// type_id= 3009 name=TCBUFFER_SEQUENCE        size=  -1  cast_from=[]  cast_to=[]
// type_id= 3010 name=TPOSE_SEQUENCE           size=  -1  cast_from=[]  cast_to=[]
// type_id= 3011 name=TNPOINT_SEQUENCE         size=  -1  cast_from=[]  cast_to=[]
// type_id= 3012 name=INTSPAN                  size=  -1  cast_from=[]  cast_to=[]
// type_id= 3013 name=FLOATSPAN                size=  -1  cast_from=[]  cast_to=[]
// type_id= 3014 name=DATESPAN                 size=  -1  cast_from=[]  cast_to=[]
// type_id= 3015 name=TSTZSPAN                 size=  -1  cast_from=[]  cast_to=[]
// type_id= 3016 name=INTSET                   size=  -1  cast_from=[]  cast_to=[]
// type_id= 3017 name=FLOATSET                 size=  -1  cast_from=[]  cast_to=[]
// type_id= 3018 name=DATESET                  size=  -1  cast_from=[]  cast_to=[]
// type_id= 3019 name=TSTZSET                  size=  -1  cast_from=[]  cast_to=[]
// type_id= 3020 name=TEXTSET                  size=  -1  cast_from=[]  cast_to=[]
// type_id= 3021 name=INTSPANSET               size=  -1  cast_from=[]  cast_to=[]
// type_id= 3022 name=FLOATSPANSET             size=  -1  cast_from=[]  cast_to=[]
// type_id= 3023 name=DATESPANSET              size=  -1  cast_from=[]  cast_to=[]
// type_id= 3024 name=TSTZSPANSET              size=  -1  cast_from=[]  cast_to=[]
// type_id= 3025 name=STBOX                    size=  48  cast_from=[]  cast_to=[]
// type_id= 3026 name=TBOX                     size=  32  cast_from=[]  cast_to=[]
// type_id= 3027 name=STBOX3D                  size=  56  cast_from=[]  cast_to=[]
// type_id= 3028 name=BITEMPORAL_BOOL          size=  -1  cast_from=[]  cast_to=[]
// type_id= 3029 name=BITEMPORAL_INT           size=  -1  cast_from=[]  cast_to=[]
// type_id= 3030 name=BITEMPORAL_FLOAT         size=  -1  cast_from=[]  cast_to=[]
// type_id= 3031 name=BITEMPORAL_TEXT          size=  -1  cast_from=[]  cast_to=[]
