// === GENERATED by ducklink-shim-codegen — do not edit by hand ===
#![allow(dead_code, unused_imports)]

//! Window-function registration.
//!
//! DuckDB exposes window functions as a special aggregate
//! variant with extra hooks for partition + frame state.

// TODO: wire window-capable aggregates.
